py_binary(
    name = "web_service",
    srcs = [
        "web_service.py",
    ],
    main = "web_service.py"
)

py_binary(
    name = "test",
    srcs = [
        "test.py",
    ],
    main = "test.py"
)